package edu.hendrix.ivyjs.manuscript

enum class SymbolEnum {
    TWELVEEIGHTTIME, TWOTWOTIME, TWOFOURTIME, THREEFOUR, THREEEIGHTTIME, FOURFOURTIME, SIXEIGHTTIME, NINEEIGHTTIME, BARLINE, CCLEF, COMMONTIME, CUTTIME, DOT, DOUBLESHARP, EIGHTHNOTE, EIGHTHREST, FCLEF, FLAT, GCLEF, HALFNOTE, NATURAL, QUARTERNOTE, QUARTERREST, SHARP, SIXTEENTHNOTE, SIXTEENTHREST, SIXTYFOURNOTE, SIXTYFOURREST, THIRTYTWONOTE, THIRTYTWOREST, WHOLEHALFREST, WHOLENOTE, UNKNOWN;
}